import { describe, it, expect, beforeAll } from 'vitest';
import { createOddMakiClient } from '../../src/client';
import { baseSepolia } from 'viem/chains';
import { http } from 'viem';

// USDC on Base Sepolia (from v1.1.0 deployment)
const USDC_ADDRESS = '0x4e7b86aff02714412956264bed10b6bdbf2ca77f';

/**
 * Live Integration Tests for Base Sepolia
 *
 * These tests verify that the SDK can correctly query all entities
 * generated by the GenerateTestData.s.sol script:
 * - 1 Venue
 * - 1 Market
 * - 4 Orders (2 matched, 1 cancelled, 1 from market buy)
 * - Multiple Trades (from matching and market buy)
 * - Top of Book updates
 * - User statistics
 * - Protocol statistics
 *
 * Prerequisites:
 * 1. Contracts deployed to Base Sepolia (v1.1.0)
 * 2. Subgraph deployed and synced
 * 3. GenerateTestData.s.sol script run successfully
 */
describe('Live Integration Tests - Base Sepolia v1.1.0', () => {
  const client = createOddMakiClient({
    chain: baseSepolia,
    transport: http(),
  });

  let testVenueId: bigint | null = null;
  let testMarketId: bigint | null = null;

  beforeAll(async () => {
    // Fetch the most recent venue and market for testing
    const venuesResponse = (await client.public.getVenues({ first: 1 })) as any;
    if (venuesResponse.venues && venuesResponse.venues.length > 0) {
      testVenueId = BigInt(venuesResponse.venues[0].venueId);

      // Get markets for this venue
      const marketsResponse = (await client.public.getMarkets({
        venueId: testVenueId,
        first: 1,
      })) as any;
      if (marketsResponse.markets && marketsResponse.markets.length > 0) {
        testMarketId = BigInt(marketsResponse.markets[0].marketId);
      }
    }
  });

  describe('Subgraph Queries', () => {
    describe('Venues', () => {
      it('should fetch venues from subgraph', async () => {
        const response = (await client.public.getVenues()) as any;

        expect(response).toBeDefined();
        expect(response.venues).toBeDefined();
        expect(Array.isArray(response.venues)).toBe(true);

        // If test data was generated, we should have at least 1 venue
        if (response.venues.length > 0) {
          const venue = response.venues[0];
          expect(venue.id).toBeDefined();
          expect(venue.venueId).toBeDefined();
          expect(venue.name).toBeDefined();
          expect(venue.operator).toBeDefined();
          expect(venue.totalMarkets).toBeDefined();

          console.log('📍 Found venue:', {
            id: venue.venueId,
            name: venue.name,
            totalMarkets: venue.totalMarkets,
          });
        }
      });
    });

    describe('Markets', () => {
      it('should fetch markets for a venue', async () => {
        if (!testVenueId) {
          console.warn('⚠️  No test venue found, skipping market tests');
          return;
        }

        const response = (await client.public.getMarkets({
          venueId: testVenueId,
          first: 10,
        })) as any;

        expect(response).toBeDefined();
        expect(response.markets).toBeDefined();
        expect(Array.isArray(response.markets)).toBe(true);

        if (response.markets.length > 0) {
          const market = response.markets[0];
          expect(market.id).toBeDefined();
          expect(market.marketId).toBeDefined();
          expect(market.question).toBeDefined();
          expect(market.outcomes).toBeDefined();
          expect(Array.isArray(market.outcomes)).toBe(true);
          expect(market.status).toBeDefined();
          expect(market.collateralToken).toBeDefined();

          console.log('📊 Found market:', {
            id: market.marketId,
            question: market.question,
            outcomes: market.outcomes,
            status: market.status,
          });
        }
      });

      it('should fetch a specific market by ID', async () => {
        if (!testMarketId) {
          console.warn('⚠️  No test market found, skipping');
          return;
        }

        const market = await client.public.getMarket(testMarketId);

        expect(market).toBeDefined();
        if (market) {
          expect(market.marketId).toBe(testMarketId.toString());
          expect(market.question).toBeDefined();
          expect(market.outcomes).toBeDefined();
          expect(market.status).toBeDefined();
          expect(market.totalVolume).toBeDefined();
          expect(market.totalOrders).toBeDefined();
          expect(market.totalFees).toBeDefined();
          expect(market.uniqueTraders).toBeDefined();

          console.log('📈 Market details:', {
            id: market.marketId,
            totalVolume: market.totalVolume,
            totalOrders: market.totalOrders,
            totalFees: market.totalFees,
            uniqueTraders: market.uniqueTraders,
          });
        }
      });
    });

    describe('Orders', () => {
      it('should fetch orders for a market', async () => {
        if (!testMarketId) {
          console.warn('⚠️  No test market found, skipping order tests');
          return;
        }

        const response = await client.public.getOrders({
          marketId: testMarketId,
          first: 20,
        });

        expect(response).toBeDefined();
        expect(response.orders).toBeDefined();
        expect(Array.isArray(response.orders)).toBe(true);

        // GenerateTestData creates 4 orders:
        // - 2 matched orders (BUY YES @ 60, BUY NO @ 45)
        // - 1 cancelled order (BUY YES @ 55)
        // - 1 from market buy
        if (response.orders.length > 0) {
          const order = response.orders[0];
          expect(order.orderId).toBeDefined();
          expect(order.trader).toBeDefined();
          expect(order.outcome).toBeDefined();
          expect(order.side).toBeDefined();
          expect(order.tick).toBeDefined();
          expect(order.amount).toBeDefined();
          expect(order.filled).toBeDefined();
          expect(order.status).toBeDefined();

          console.log(`📝 Found ${response.orders.length} orders`);
          console.log('First order:', {
            id: order.orderId,
            side: order.side,
            tick: order.tick,
            amount: order.amount,
            filled: order.filled,
            status: order.status,
          });

          // Check for different order statuses
          const statuses = response.orders.map((o) => o.status);
          const uniqueStatuses = [...new Set(statuses)];
          console.log('Order statuses found:', uniqueStatuses);

          // We expect at least one cancelled order from test data
          expect(statuses).toContain('Cancelled');
        }
      });
    });

    describe('Trades', () => {
      it('should fetch trade history for a market', async () => {
        if (!testMarketId) {
          console.warn('⚠️  No test market found, skipping trade tests');
          return;
        }

        const response = await client.public.getTradeHistory({
          marketId: testMarketId,
          first: 20,
        });

        expect(response).toBeDefined();
        expect(response.trades).toBeDefined();
        expect(Array.isArray(response.trades)).toBe(true);

        // GenerateTestData creates trades from:
        // - Matching 2 orders
        // - Market buy execution
        if (response.trades.length > 0) {
          const trade = response.trades[0];
          expect(trade.id).toBeDefined();
          expect(trade.outcome).toBeDefined();
          expect(trade.side).toBeDefined();
          expect(trade.tick).toBeDefined();
          expect(trade.amount).toBeDefined();
          expect(trade.cost).toBeDefined();
          expect(trade.fees).toBeDefined();
          expect(trade.tradeType).toBeDefined();
          expect(trade.timestamp).toBeDefined();

          console.log(`💱 Found ${response.trades.length} trades`);
          console.log('Recent trade:', {
            outcome: trade.outcome,
            side: trade.side,
            tick: trade.tick,
            amount: trade.amount,
            type: trade.tradeType,
          });

          // Check for different trade types
          const tradeTypes = response.trades.map((t) => t.tradeType);
          const uniqueTradeTypes = [...new Set(tradeTypes)];
          console.log('Trade types found:', uniqueTradeTypes);

          // We expect both Match and MarketBuy from test data
          expect(uniqueTradeTypes.length).toBeGreaterThan(0);
        }
      });
    });

    describe('Order Book State', () => {
      it('should fetch top of book for a market', async () => {
        if (!testMarketId) {
          console.warn('⚠️  No test market found, skipping top of book tests');
          return;
        }

        const response = await client.public.getTopOfBook(testMarketId);

        expect(response).toBeDefined();
        expect(response.topOfBooks).toBeDefined();
        expect(Array.isArray(response.topOfBooks)).toBe(true);

        // Top of book entries exist for each outcome + side combination
        if (response.topOfBooks.length > 0) {
          const tob = response.topOfBooks[0];
          expect(tob.outcome).toBeDefined();
          expect(tob.side).toBeDefined();
          expect(tob.topTick).toBeDefined();
          expect(tob.updatedAt).toBeDefined();

          console.log(
            `📖 Found ${response.topOfBooks.length} top of book entries`
          );
          response.topOfBooks.forEach((entry) => {
            console.log(
              `  Outcome ${entry.outcome} ${entry.side}: ${entry.topTick} ticks`
            );
          });
        }
      });
    });

    describe('User Statistics', () => {
      it('should fetch user data by address', async () => {
        // Use the deployer address from Base Sepolia
        const deployerAddress = '0xd2632c0225F3ffBF070AA2252A558c3552aB3b54';

        const response = await client.public.getUser(deployerAddress);

        expect(response).toBeDefined();

        if (response.user) {
          const user = response.user;
          expect(user.address).toBe(deployerAddress.toLowerCase());
          expect(user.totalOrdersPlaced).toBeDefined();
          expect(user.totalVolume).toBeDefined();
          expect(user.totalMarkets).toBeDefined();
          expect(user.firstSeenAt).toBeDefined();
          expect(user.lastSeenAt).toBeDefined();

          console.log('👤 User statistics:', {
            address: user.address,
            ordersPlaced: user.totalOrdersPlaced,
            volume: user.totalVolume,
            marketsCreated: user.totalMarkets,
          });

          // From test data, deployer should have placed orders
          expect(BigInt(user.totalOrdersPlaced)).toBeGreaterThan(0n);
        } else {
          console.warn('⚠️  User not found in subgraph');
        }
      });
    });

    describe('Protocol Statistics', () => {
      it('should fetch protocol-wide statistics', async () => {
        const response = await client.public.getProtocolStats();

        expect(response).toBeDefined();

        if (response.protocol) {
          const stats = response.protocol;
          expect(stats.id).toBe('octopus-protocol');
          expect(stats.totalVenues).toBeDefined();
          expect(stats.totalMarkets).toBeDefined();
          expect(stats.totalVolume).toBeDefined();
          expect(stats.totalFees).toBeDefined();
          expect(stats.totalUsers).toBeDefined();
          expect(stats.updatedAt).toBeDefined();

          console.log('🌐 Protocol statistics:', {
            venues: stats.totalVenues,
            markets: stats.totalMarkets,
            volume: stats.totalVolume,
            fees: stats.totalFees,
            users: stats.totalUsers,
            lastUpdated: stats.updatedAt,
          });

          // If test data exists, we should have activity
          if (testVenueId && testMarketId) {
            expect(BigInt(stats.totalVenues)).toBeGreaterThan(0n);
            expect(BigInt(stats.totalMarkets)).toBeGreaterThan(0n);
          }
        } else {
          console.warn('⚠️  Protocol entity not found in subgraph');
        }
      });
    });
  });

  describe('RPC Queries (Token Operations)', () => {
    it('should fetch USDC decimals from RPC', async () => {
      const decimals = await client.token.getDecimals(USDC_ADDRESS);
      expect(decimals).toBe(6);
      console.log('💰 USDC decimals:', decimals);
    });

    it('should fetch USDC symbol from RPC', async () => {
      const symbol = await client.token.getSymbol(USDC_ADDRESS);
      expect(symbol).toBe('USDC');
      console.log('💰 USDC symbol:', symbol);
    });

    it('should fetch USDC name from RPC', async () => {
      const name = await client.token.getName(USDC_ADDRESS);
      expect(name).toBeDefined();
      console.log('💰 USDC name:', name);
    });
  });
});
